DROP DATABASE IF EXISTS booksdb;
DROP USER IF EXISTS 'bookadmin'@'%';
DROP USER IF EXISTS 'bookuser'@'%';
CREATE DATABASE IF NOT EXISTS booksdb CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'bookadmin'@'%' IDENTIFIED BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT,
    TRIGGER ON booksdb.* to 'bookadmin'@'%';
CREATE USER IF NOT EXISTS 'bookuser'@'%' IDENTIFIED BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE ON booksdb.* to 'bookadmin'@'%';
FLUSH PRIVILEGES;